import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";

import AppProvider from "~/providers/AppProvider";

export const metadata = {
  title: "Create Devviantex App",
  description: "Generated by extended version of create-t3-app by Devviantex",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <TRPCReactProvider>
          <AppProvider>{children}</AppProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
